flowchart TD
    %% Nodes
    cluster
    db_bar
    db_foo
    service_bar
    service_foo

    %% Links
    service_bar -->|DB| db_bar
    service_foo -->|DB| db_foo
    service_foo -->|API| service_bar
