flowchart LR
    %% Nodes
    app_bar
    app_foo
    cluster[Container Hosting]
    db_bar[Bar Database]
    db_foo[Foo Database]
    service_bar[Bar Service]
    service_foo[Foo Service]

    %% Links
    service_bar -->|DB| db_bar
    service_foo -->|DB| db_foo
    service_foo -->|Uses| service_bar
