flowchart TD
    %% Node Styles
    classDef style0 fill:#abcabc,color:#F00000,stroke-width:2px,font-size:12px,rx:5px;
    classDef style1 padding:10px,ry:5px;

    %% Nodes
    app_bar
    app_foo
    cluster
    db_bar
    db_foo
    service_bar
    service_foo

    %% Node Styles
    class service_bar,service_foo style0
    class db_bar,db_foo style1

    %% Links
    service_bar -->|DB| db_bar
    service_foo -->|DB| db_foo
    service_foo -->|Uses| service_bar
